
// Generated by Cadence Genus(TM) Synthesis Solution 17.20-p003_1
// Generated on: Sep 29 2020 21:38:28 -03 (Sep 30 2020 00:38:28 UTC)

// Verification Directory fv/uart 

module uart(clk16x, clrn, rdn, d_out, r_ready, rxd, parity_error,
     frame_error, wrn, d_in, t_empty, txd, cnt16x, no_bits_rcvd,
     r_buffer, r_clk1x, sampling, r_data, no_bits_sent, t_buffer,
     t_clk1x, sending, t_data);
  input clk16x, clrn, rdn, rxd, wrn;
  input [7:0] d_in;
  output [7:0] d_out, r_data, t_buffer, t_data;
  output r_ready, parity_error, frame_error, t_empty, txd, r_clk1x,
       sampling, t_clk1x, sending;
  output [3:0] cnt16x, no_bits_rcvd, no_bits_sent;
  output [10:0] r_buffer;
  wire clk16x, clrn, rdn, rxd, wrn;
  wire [7:0] d_in;
  wire [7:0] d_out, r_data, t_buffer, t_data;
  wire r_ready, parity_error, frame_error, t_empty, txd, r_clk1x,
       sampling, t_clk1x, sending;
  wire [3:0] cnt16x, no_bits_rcvd, no_bits_sent;
  wire [10:0] r_buffer;
  wire [3:0] recver_sampling_place;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, recver_n_64, recver_n_65, recver_n_1157,
       recver_n_1159;
  wire recver_n_1162, recver_n_1163, recver_n_1164, recver_n_1165,
       recver_n_1170, recver_n_1180, recver_n_1181, recver_n_1182;
  wire recver_n_1183, recver_n_1185, recver_n_1187, recver_n_1190,
       recver_n_1192, recver_n_1197, recver_n_1199, recver_n_1201;
  wire recver_n_1202, recver_n_1204, recver_n_1205, recver_n_1206,
       recver_n_1207, recver_n_1208, recver_n_1211, recver_n_1213;
  wire recver_n_1214, recver_n_1219, recver_n_1222, recver_n_1224,
       recver_n_1226, recver_n_1228, recver_n_1232, recver_n_1235;
  wire recver_n_1238, recver_n_1240, recver_n_1242, recver_n_1244,
       recver_n_1246, recver_n_1249, recver_n_1250, recver_n_1251;
  wire recver_n_1252, recver_n_1254, recver_n_1255, recver_n_1256,
       recver_n_1258, recver_n_1260, recver_n_1263, recver_n_1264;
  wire recver_n_1265, recver_n_1266, recver_n_1267, recver_n_1268,
       recver_n_1270, recver_n_1271, recver_n_1272, recver_n_1274;
  wire recver_n_1276, recver_n_1277, recver_n_1285, recver_n_1287,
       recver_n_1306, recver_n_1307, recver_rxd_new, recver_rxd_old;
  wire sender_clrn_buf, sender_clrn_buf_clean, sender_load_t_buffer,
       sender_n_127, sender_wrn_buf, sender_wrn_buf_clean;
  assign t_clk1x = cnt16x[3];
  assign r_buffer[0] = 1'b0;
  assign r_buffer[1] = 1'b0;
  assign r_buffer[2] = 1'b0;
  assign r_buffer[3] = 1'b0;
  assign r_buffer[4] = 1'b0;
  assign r_buffer[5] = 1'b0;
  assign r_buffer[6] = 1'b0;
  assign r_buffer[7] = 1'b0;
  assign r_buffer[8] = 1'b0;
  assign r_buffer[9] = 1'b0;
  assign r_buffer[10] = 1'b0;
  DFSNQD2BWP7T sender_txd_reg(.SDN (sending), .CP (cnt16x[3]), .D
       (n_30), .Q (txd));
  AO221D0BWP7T g540(.A1 (n_29), .A2 (no_bits_sent[3]), .B1 (n_26), .B2
       (no_bits_sent[2]), .C (n_28), .Z (n_30));
  AO221D0BWP7T g541(.A1 (n_27), .A2 (no_bits_sent[0]), .B1 (n_19), .B2
       (t_buffer[7]), .C (no_bits_sent[1]), .Z (n_29));
  NR3D0BWP7T g542(.A1 (n_25), .A2 (no_bits_sent[3]), .A3
       (no_bits_sent[2]), .ZN (n_28));
  CKXOR2D0BWP7T g543(.A1 (n_22), .A2 (n_23), .Z (n_27));
  IND2D0BWP7T g544(.A1 (no_bits_sent[3]), .B1 (n_24), .ZN (n_26));
  DFQD1BWP7T sender_wrn_buf_clean_reg(.CP (clk16x), .D (sender_n_127),
       .Q (sender_wrn_buf_clean));
  MUX3ND0BWP7T g546(.I0 (t_buffer[0]), .I1 (t_buffer[2]), .I2 (n_20),
       .S0 (no_bits_sent[1]), .S1 (n_19), .ZN (n_25));
  MUX4ND0BWP7T g547(.I0 (t_buffer[3]), .I1 (t_buffer[5]), .I2
       (t_buffer[4]), .I3 (t_buffer[6]), .S0 (no_bits_sent[1]), .S1
       (no_bits_sent[0]), .ZN (n_24));
  XOR4D0BWP7T g548(.A1 (t_buffer[5]), .A2 (t_buffer[3]), .A3
       (t_buffer[6]), .A4 (t_buffer[1]), .Z (n_23));
  XOR4D0BWP7T g549(.A1 (t_buffer[4]), .A2 (t_buffer[2]), .A3
       (t_buffer[7]), .A4 (t_buffer[0]), .Z (n_22));
  ND2D0BWP7T g550(.A1 (sender_clrn_buf), .A2 (sender_wrn_buf), .ZN
       (sender_n_127));
  LNQD1BWP7T sender_clrn_buf_reg(.EN (n_21), .D (clrn), .Q
       (sender_clrn_buf));
  INR2D0BWP7T g552(.A1 (clrn), .B1 (sender_clrn_buf_clean), .ZN (n_21));
  AN2D1BWP7T g553(.A1 (no_bits_sent[1]), .A2 (t_buffer[1]), .Z (n_20));
  INVD1BWP7T g554(.I (no_bits_sent[0]), .ZN (n_19));
  EDFCNQD1BWP7T \cnt16x_reg[3] (.CDN (clrn), .CP (clk16x), .D (n_1), .E
       (n_16), .Q (cnt16x[3]));
  DFKCNQD2BWP7T sender_sending_reg(.CP (clk16x), .CN (sender_clrn_buf),
       .D (n_14), .Q (sending));
  DFCNQD2BWP7T \sender_no_bits_sent_reg[3] (.CDN (sending), .CP
       (cnt16x[3]), .D (n_15), .Q (no_bits_sent[3]));
  DFCNQD2BWP7T \cnt16x_reg[2] (.CDN (clrn), .CP (clk16x), .D (n_17), .Q
       (cnt16x[2]));
  HA1D0BWP7T g508(.A (cnt16x[2]), .B (n_8), .CO (n_16), .S (n_17));
  EDFKCNQD2BWP7T \sender_t_buffer_reg[1] (.CP (clk16x), .CN
       (sender_clrn_buf), .D (t_data[1]), .E (n_7), .Q (t_buffer[1]));
  EDFKCNQD2BWP7T \sender_t_buffer_reg[0] (.CP (clk16x), .CN
       (sender_clrn_buf), .D (t_data[0]), .E (n_7), .Q (t_buffer[0]));
  EDFKCNQD2BWP7T \sender_t_buffer_reg[3] (.CP (clk16x), .CN
       (sender_clrn_buf), .D (t_data[3]), .E (n_7), .Q (t_buffer[3]));
  EDFKCNQD2BWP7T \sender_t_buffer_reg[2] (.CP (clk16x), .CN
       (sender_clrn_buf), .D (t_data[2]), .E (n_7), .Q (t_buffer[2]));
  SDFCNQD2BWP7T \sender_no_bits_sent_reg[2] (.CDN (sending), .CP
       (cnt16x[3]), .D (n_12), .SI (n_11), .SE (no_bits_sent[2]), .Q
       (no_bits_sent[2]));
  AO221D0BWP7T g514(.A1 (n_12), .A2 (n_4), .B1 (n_11), .B2
       (no_bits_sent[3]), .C (n_6), .Z (n_15));
  AO21D0BWP7T g515(.A1 (sending), .A2 (n_13), .B (n_7), .Z (n_14));
  EDFKCNQD2BWP7T \sender_t_buffer_reg[6] (.CP (clk16x), .CN
       (sender_clrn_buf), .D (t_data[6]), .E (n_7), .Q (t_buffer[6]));
  EDFKCNQD2BWP7T \sender_t_buffer_reg[7] (.CP (clk16x), .CN
       (sender_clrn_buf), .D (t_data[7]), .E (n_7), .Q (t_buffer[7]));
  EDFKCNQD2BWP7T \sender_t_buffer_reg[4] (.CP (clk16x), .CN
       (sender_clrn_buf), .D (t_data[4]), .E (n_7), .Q (t_buffer[4]));
  EDFKCNQD2BWP7T \sender_t_buffer_reg[5] (.CP (clk16x), .CN
       (sender_clrn_buf), .D (t_data[5]), .E (n_7), .Q (t_buffer[5]));
  SDFKSNQD2BWP7T sender_t_empty_reg(.CP (clk16x), .D (t_empty), .SN
       (n_5), .SI (n_0), .SE (sender_n_127), .Q (t_empty));
  SDFKCNQD1BWP7T sender_load_t_buffer_reg(.CP (clk16x), .CN
       (sender_load_t_buffer), .D (n_5), .SI (sender_clrn_buf), .SE
       (sender_n_127), .Q (sender_load_t_buffer));
  EDFKCNQD2BWP7T \sender_t_data_reg[0] (.CP (clk16x), .CN
       (sender_clrn_buf), .D (d_in[0]), .E (n_2), .Q (t_data[0]));
  DFCNQD2BWP7T \cnt16x_reg[1] (.CDN (clrn), .CP (clk16x), .D (n_9), .Q
       (cnt16x[1]));
  DFCNQD2BWP7T \sender_no_bits_sent_reg[1] (.CDN (sending), .CP
       (cnt16x[3]), .D (n_10), .Q (no_bits_sent[1]));
  EDFKCNQD2BWP7T \sender_t_data_reg[1] (.CP (clk16x), .CN
       (sender_clrn_buf), .D (d_in[1]), .E (n_2), .Q (t_data[1]));
  EDFKCNQD2BWP7T \sender_t_data_reg[2] (.CP (clk16x), .CN
       (sender_clrn_buf), .D (d_in[2]), .E (n_2), .Q (t_data[2]));
  ND3D0BWP7T g527(.A1 (n_12), .A2 (n_6), .A3 (sender_wrn_buf), .ZN
       (n_13));
  EDFKCNQD2BWP7T \sender_t_data_reg[4] (.CP (clk16x), .CN
       (sender_clrn_buf), .D (d_in[4]), .E (n_2), .Q (t_data[4]));
  EDFKCNQD2BWP7T \sender_t_data_reg[5] (.CP (clk16x), .CN
       (sender_clrn_buf), .D (d_in[5]), .E (n_2), .Q (t_data[5]));
  EDFKCNQD2BWP7T \sender_t_data_reg[6] (.CP (clk16x), .CN
       (sender_clrn_buf), .D (d_in[6]), .E (n_2), .Q (t_data[6]));
  EDFKCNQD2BWP7T \sender_t_data_reg[7] (.CP (clk16x), .CN
       (sender_clrn_buf), .D (d_in[7]), .E (n_2), .Q (t_data[7]));
  EDFKCNQD2BWP7T \sender_t_data_reg[3] (.CP (clk16x), .CN
       (sender_clrn_buf), .D (d_in[3]), .E (n_2), .Q (t_data[3]));
  INVD1BWP7T g533(.I (n_12), .ZN (n_11));
  HA1D0BWP7T g534(.A (no_bits_sent[0]), .B (no_bits_sent[1]), .CO
       (n_12), .S (n_10));
  HA1D0BWP7T g535(.A (cnt16x[0]), .B (cnt16x[1]), .CO (n_8), .S (n_9));
  LHQD1BWP7T sender_wrn_buf_reg(.E (n_3), .D (wrn), .Q
       (sender_wrn_buf));
  NR2XD0BWP7T g537(.A1 (n_5), .A2 (n_2), .ZN (n_7));
  DFQD1BWP7T sender_clrn_buf_clean_reg(.CP (clk16x), .D (n_0), .Q
       (sender_clrn_buf_clean));
  DFSNQD1BWP7T \cnt16x_reg[0] (.SDN (clrn), .CP (clk16x), .D
       (cnt16x[0]), .Q (n_18));
  DFSND2BWP7T \sender_no_bits_sent_reg[0] (.SDN (sending), .CP
       (cnt16x[3]), .D (no_bits_sent[0]), .Q (UNCONNECTED), .QN
       (no_bits_sent[0]));
  INR2D0BWP7T g555(.A1 (no_bits_sent[2]), .B1 (no_bits_sent[3]), .ZN
       (n_4));
  IND2D0BWP7T g556(.A1 (sender_wrn_buf_clean), .B1 (wrn), .ZN (n_3));
  INR2D0BWP7T g557(.A1 (no_bits_sent[3]), .B1 (no_bits_sent[2]), .ZN
       (n_6));
  IND2D1BWP7T g558(.A1 (sending), .B1 (sender_load_t_buffer), .ZN
       (n_5));
  INVD1BWP7T g559(.I (sender_wrn_buf), .ZN (n_2));
  INVD2BWP7T g560(.I (n_18), .ZN (cnt16x[0]));
  INVD0BWP7T g561(.I (cnt16x[3]), .ZN (n_1));
  INVD1BWP7T g551(.I (sender_clrn_buf), .ZN (n_0));
  DFSNQD1BWP7T recver_rxd_old_reg(.SDN (clrn), .CP (clk16x), .D
       (recver_rxd_new), .Q (recver_rxd_old));
  BUFTD2BWP7T recver_g126(.I (r_data[0]), .OE (recver_n_65), .Z
       (d_out[0]));
  BUFTD2BWP7T recver_g119(.I (r_data[7]), .OE (recver_n_65), .Z
       (d_out[7]));
  BUFTD2BWP7T recver_g120(.I (r_data[6]), .OE (recver_n_65), .Z
       (d_out[6]));
  DFSNQD1BWP7T recver_rxd_new_reg(.SDN (clrn), .CP (clk16x), .D (rxd),
       .Q (recver_rxd_new));
  BUFTD2BWP7T recver_g121(.I (r_data[5]), .OE (recver_n_65), .Z
       (d_out[5]));
  BUFTD2BWP7T recver_g123(.I (r_data[3]), .OE (recver_n_65), .Z
       (d_out[3]));
  BUFTD2BWP7T recver_g122(.I (r_data[4]), .OE (recver_n_65), .Z
       (d_out[4]));
  BUFTD2BWP7T recver_g124(.I (r_data[2]), .OE (recver_n_65), .Z
       (d_out[2]));
  BUFTD2BWP7T recver_g125(.I (r_data[1]), .OE (recver_n_65), .Z
       (d_out[1]));
  INVD0BWP7T recver_g667(.I (clrn), .ZN (recver_n_64));
  INVD1BWP7T recver_g668(.I (rdn), .ZN (recver_n_65));
  DFCNQD2BWP7T recver_parity_error_reg(.CDN (recver_n_1271), .CP
       (clk16x), .D (recver_n_1157), .Q (parity_error));
  DFSND1BWP7T recver_clk1x_reg(.SDN (clrn), .CP (clk16x), .D
       (recver_n_1159), .Q (UNCONNECTED0), .QN (r_clk1x));
  AO21D0BWP7T recver_g2815(.A1 (recver_n_1251), .A2 (recver_n_1162), .B
       (parity_error), .Z (recver_n_1157));
  OAI211D1BWP7T recver_g2816(.A1 (r_clk1x), .A2 (recver_n_1202), .B
       (recver_n_1163), .C (sampling), .ZN (recver_n_1159));
  XNR4D0BWP7T recver_g2817(.A1 (r_buffer[3]), .A2 (r_buffer[2]), .A3
       (recver_n_1170), .A4 (recver_n_1260), .ZN (recver_n_1162));
  ND4D0BWP7T recver_g2818(.A1 (recver_n_1164), .A2 (recver_n_1165), .A3
       (recver_n_1182), .A4 (recver_n_1254), .ZN (recver_n_1163));
  SDFQD0BWP7T \recver_r_buffer_reg[10] (.CP (r_clk1x), .D (rxd), .SI
       (r_buffer[10]), .SE (recver_n_1204), .Q (r_buffer[10]));
  MAOI22D0BWP7T recver_g2820(.A1 (recver_n_1255), .A2
       (recver_sampling_place[0]), .B1 (recver_n_1180), .B2
       (cnt16x[3]), .ZN (recver_n_1164));
  MAOI22D0BWP7T recver_g2821(.A1 (recver_n_1180), .A2 (cnt16x[3]), .B1
       (recver_n_1255), .B2 (recver_sampling_place[0]), .ZN
       (recver_n_1165));
  XOR3D0BWP7T recver_g2822(.A1 (r_buffer[4]), .A2 (recver_n_1222), .A3
       (r_buffer[8]), .Z (recver_n_1170));
  DFQD1BWP7T \recver_r_buffer_reg[8] (.CP (r_clk1x), .D
       (recver_n_1181), .Q (r_buffer[8]));
  DFD1BWP7T \recver_r_buffer_reg[5] (.CP (r_clk1x), .D (recver_n_1183),
       .Q (UNCONNECTED1), .QN (r_buffer[5]));
  DFD1BWP7T \recver_r_buffer_reg[4] (.CP (r_clk1x), .D (recver_n_1190),
       .Q (UNCONNECTED2), .QN (r_buffer[4]));
  DFQD1BWP7T \recver_r_buffer_reg[9] (.CP (r_clk1x), .D
       (recver_n_1192), .Q (r_buffer[9]));
  SDFQD0BWP7T \recver_r_buffer_reg[2] (.CP (r_clk1x), .D (rxd), .SI
       (r_buffer[2]), .SE (recver_n_1208), .Q (r_buffer[2]));
  DFQD1BWP7T \recver_r_buffer_reg[1] (.CP (r_clk1x), .D
       (recver_n_1185), .Q (r_buffer[1]));
  DFQD1BWP7T \recver_r_buffer_reg[0] (.CP (r_clk1x), .D
       (recver_n_1187), .Q (r_buffer[0]));
  SDFQD0BWP7T \recver_r_buffer_reg[6] (.CP (r_clk1x), .D (rxd), .SI
       (r_buffer[6]), .SE (recver_n_1224), .Q (r_buffer[6]));
  SDFQD0BWP7T \recver_r_buffer_reg[7] (.CP (r_clk1x), .D (r_buffer[7]),
       .SI (rxd), .SE (recver_n_1246), .Q (r_buffer[7]));
  SDFQD0BWP7T \recver_r_buffer_reg[3] (.CP (r_clk1x), .D (rxd), .SI
       (r_buffer[3]), .SE (recver_n_1235), .Q (r_buffer[3]));
  EDFCNQD2BWP7T \recver_r_data_reg[1] (.CDN (clrn), .CP (clk16x), .D
       (r_buffer[2]), .E (recver_n_1228), .Q (r_data[1]));
  EDFCNQD2BWP7T \recver_r_data_reg[2] (.CDN (clrn), .CP (clk16x), .D
       (r_buffer[3]), .E (recver_n_1228), .Q (r_data[2]));
  EDFCNQD2BWP7T \recver_r_data_reg[3] (.CDN (clrn), .CP (clk16x), .D
       (r_buffer[4]), .E (recver_n_1228), .Q (r_data[3]));
  EDFCNQD2BWP7T \recver_r_data_reg[4] (.CDN (clrn), .CP (clk16x), .D
       (r_buffer[5]), .E (recver_n_1228), .Q (r_data[4]));
  EDFCNQD2BWP7T \recver_r_data_reg[5] (.CDN (clrn), .CP (clk16x), .D
       (r_buffer[6]), .E (recver_n_1228), .Q (r_data[5]));
  EDFCNQD2BWP7T \recver_r_data_reg[6] (.CDN (clrn), .CP (clk16x), .D
       (r_buffer[7]), .E (recver_n_1228), .Q (r_data[6]));
  EDFCNQD2BWP7T \recver_r_data_reg[7] (.CDN (clrn), .CP (clk16x), .D
       (r_buffer[8]), .E (recver_n_1228), .Q (r_data[7]));
  EDFCNQD2BWP7T \recver_r_data_reg[0] (.CDN (clrn), .CP (clk16x), .D
       (r_buffer[1]), .E (recver_n_1228), .Q (r_data[0]));
  EDFCNQD2BWP7T recver_sampling_reg(.CDN (clrn), .CP (clk16x), .D
       (recver_n_1265), .E (recver_n_1244), .Q (sampling));
  OAI21D0BWP7T recver_g2842(.A1 (recver_n_1238), .A2 (recver_n_1263),
       .B (recver_n_1199), .ZN (recver_n_1181));
  XNR2D1BWP7T recver_g2843(.A1 (recver_n_1205), .A2 (cnt16x[2]), .ZN
       (recver_n_1182));
  AOI22D0BWP7T recver_g2844(.A1 (recver_n_1240), .A2 (recver_n_1267),
       .B1 (recver_n_1213), .B2 (r_buffer[5]), .ZN (recver_n_1183));
  MOAI22D0BWP7T recver_g2845(.A1 (recver_n_1226), .A2 (recver_n_1266),
       .B1 (recver_n_1207), .B2 (r_buffer[1]), .ZN (recver_n_1185));
  OAI21D0BWP7T recver_g2846(.A1 (recver_n_1226), .A2 (recver_n_1263),
       .B (recver_n_1201), .ZN (recver_n_1187));
  AOI22D0BWP7T recver_g2847(.A1 (recver_n_1240), .A2 (recver_n_1264),
       .B1 (recver_n_1211), .B2 (r_buffer[4]), .ZN (recver_n_1190));
  OAI21D0BWP7T recver_g2848(.A1 (recver_n_1238), .A2 (recver_n_1266),
       .B (recver_n_1197), .ZN (recver_n_1192));
  XNR2D1BWP7T recver_g2849(.A1 (recver_n_1206), .A2 (recver_n_1285),
       .ZN (recver_n_1180));
  EDFQD1BWP7T \recver_sampling_place_reg[1] (.CP (clk16x), .D
       (cnt16x[1]), .E (recver_n_1242), .Q (recver_sampling_place[1]));
  EDFQD1BWP7T \recver_sampling_place_reg[3] (.CP (clk16x), .D
       (cnt16x[3]), .E (recver_n_1242), .Q (recver_sampling_place[3]));
  EDFQD1BWP7T \recver_sampling_place_reg[2] (.CP (clk16x), .D
       (cnt16x[2]), .E (recver_n_1242), .Q (recver_sampling_place[2]));
  EDFQD1BWP7T \recver_sampling_place_reg[0] (.CP (clk16x), .D
       (cnt16x[0]), .E (recver_n_1242), .Q (recver_sampling_place[0]));
  OAI21D0BWP7T recver_g2854(.A1 (recver_n_1238), .A2 (recver_n_1306),
       .B (r_buffer[9]), .ZN (recver_n_1197));
  DFSND2BWP7T recver_frame_error_reg(.SDN (recver_n_1271), .CP
       (clk16x), .D (recver_n_1219), .Q (UNCONNECTED3), .QN
       (frame_error));
  DFCNQD2BWP7T \recver_no_bits_rcvd_reg[3] (.CDN (sampling), .CP
       (r_clk1x), .D (recver_n_1214), .Q (no_bits_rcvd[3]));
  OAI21D0BWP7T recver_g2857(.A1 (recver_n_1238), .A2 (no_bits_rcvd[0]),
       .B (r_buffer[8]), .ZN (recver_n_1199));
  OAI21D0BWP7T recver_g2858(.A1 (recver_n_1226), .A2 (no_bits_rcvd[0]),
       .B (r_buffer[0]), .ZN (recver_n_1201));
  INR4D0BWP7T recver_g2859(.A1 (recver_n_1255), .B1 (recver_n_1256),
       .B2 (recver_n_1258), .B3 (recver_n_1254), .ZN (recver_n_1202));
  ND3D0BWP7T recver_g2860(.A1 (sampling), .A2 (recver_n_1274), .A3
       (recver_n_1272), .ZN (recver_n_1204));
  HA1D0BWP7T recver_g2861(.A (recver_sampling_place[2]), .B
       (recver_n_1268), .CO (recver_n_1206), .S (recver_n_1205));
  IND2D0BWP7T recver_g2862(.A1 (recver_n_1226), .B1 (no_bits_rcvd[0]),
       .ZN (recver_n_1207));
  ND2D0BWP7T recver_g2863(.A1 (recver_n_1307), .A2 (recver_n_1274), .ZN
       (recver_n_1208));
  DFCNQD2BWP7T recver_r_ready_reg(.CDN (recver_n_1271), .CP (clk16x),
       .D (recver_n_1232), .Q (r_ready));
  SDFCNQD2BWP7T \recver_no_bits_rcvd_reg[2] (.CDN (sampling), .CP
       (r_clk1x), .D (recver_n_1276), .SI (recver_n_1277), .SE
       (no_bits_rcvd[2]), .Q (no_bits_rcvd[2]));
  DFCNQD2BWP7T \recver_no_bits_rcvd_reg[1] (.CDN (sampling), .CP
       (r_clk1x), .D (recver_n_1252), .Q (no_bits_rcvd[1]));
  ND2D0BWP7T recver_g2867(.A1 (recver_n_1240), .A2 (recver_n_1306), .ZN
       (recver_n_1211));
  ND2D0BWP7T recver_g2868(.A1 (recver_n_1240), .A2 (no_bits_rcvd[0]),
       .ZN (recver_n_1213));
  AO221D0BWP7T recver_g2869(.A1 (recver_n_1276), .A2 (recver_n_1270),
       .B1 (recver_n_1277), .B2 (no_bits_rcvd[3]), .C (recver_n_1272),
       .Z (recver_n_1214));
  IAO21D0BWP7T recver_g2870(.A1 (recver_n_1250), .A2 (r_buffer[10]), .B
       (frame_error), .ZN (recver_n_1219));
  XOR3D0BWP7T recver_g2871(.A1 (r_buffer[1]), .A2 (r_buffer[7]), .A3
       (r_buffer[9]), .Z (recver_n_1222));
  IND2D0BWP7T recver_g2872(.A1 (recver_n_1249), .B1 (recver_n_1274),
       .ZN (recver_n_1224));
  IND2D1BWP7T recver_g2873(.A1 (r_ready), .B1 (recver_n_1250), .ZN
       (recver_n_1232));
  ND2D0BWP7T recver_g2874(.A1 (recver_n_1307), .A2 (recver_n_1276), .ZN
       (recver_n_1235));
  IND2D0BWP7T recver_g2875(.A1 (no_bits_rcvd[1]), .B1 (recver_n_1307),
       .ZN (recver_n_1226));
  NR2XD0BWP7T recver_g2876(.A1 (recver_n_1250), .A2 (recver_n_65), .ZN
       (recver_n_1228));
  IND2D1BWP7T recver_g2877(.A1 (recver_n_1265), .B1 (recver_n_1250),
       .ZN (recver_n_1244));
  NR2D0BWP7T recver_g2878(.A1 (recver_n_1249), .A2 (recver_n_1277), .ZN
       (recver_n_1246));
  IND3D0BWP7T recver_g2879(.A1 (no_bits_rcvd[1]), .B1 (recver_n_1272),
       .B2 (sampling), .ZN (recver_n_1238));
  NR2D0BWP7T recver_g2880(.A1 (recver_n_1249), .A2 (no_bits_rcvd[1]),
       .ZN (recver_n_1240));
  INR3D0BWP7T recver_g2881(.A1 (recver_n_1265), .B1 (recver_n_64), .B2
       (sampling), .ZN (recver_n_1242));
  INVD0BWP7T recver_g2882(.I (recver_n_1250), .ZN (recver_n_1251));
  AO21D0BWP7T recver_g2883(.A1 (no_bits_rcvd[0]), .A2 (recver_n_1287),
       .B (recver_n_1274), .Z (recver_n_1252));
  ND2D0BWP7T recver_g2885(.A1 (sampling), .A2 (recver_n_1270), .ZN
       (recver_n_1249));
  ND2D0BWP7T recver_g2886(.A1 (recver_n_1276), .A2 (recver_n_1272), .ZN
       (recver_n_1250));
  CKXOR2D1BWP7T recver_g2887(.A1 (recver_n_1285), .A2 (cnt16x[3]), .Z
       (recver_n_1256));
  CKXOR2D1BWP7T recver_g2888(.A1 (cnt16x[2]), .A2
       (recver_sampling_place[2]), .Z (recver_n_1258));
  XNR2D1BWP7T recver_g2889(.A1 (r_buffer[6]), .A2 (r_buffer[5]), .ZN
       (recver_n_1260));
  CKXOR2D1BWP7T recver_g2890(.A1 (cnt16x[0]), .A2
       (recver_sampling_place[0]), .Z (recver_n_1254));
  XNR2D1BWP7T recver_g2891(.A1 (cnt16x[1]), .A2
       (recver_sampling_place[1]), .ZN (recver_n_1255));
  INVD0BWP7T recver_g2892(.I (recver_n_1263), .ZN (recver_n_1264));
  INVD0BWP7T recver_g2893(.I (recver_n_1266), .ZN (recver_n_1267));
  AN2D1BWP7T recver_g2894(.A1 (recver_sampling_place[1]), .A2
       (recver_sampling_place[0]), .Z (recver_n_1268));
  ND2D0BWP7T recver_g2895(.A1 (recver_n_1306), .A2 (rxd), .ZN
       (recver_n_1263));
  INR2XD0BWP7T recver_g2896(.A1 (recver_rxd_old), .B1 (recver_rxd_new),
       .ZN (recver_n_1265));
  ND2D0BWP7T recver_g2897(.A1 (no_bits_rcvd[0]), .A2 (rxd), .ZN
       (recver_n_1266));
  DFCNQD2BWP7T \recver_no_bits_rcvd_reg[0] (.CDN (sampling), .CP
       (r_clk1x), .D (recver_n_1306), .Q (no_bits_rcvd[0]));
  INVD1BWP7T recver_g2899(.I (recver_n_1276), .ZN (recver_n_1277));
  INR2D0BWP7T recver_g2900(.A1 (no_bits_rcvd[2]), .B1
       (no_bits_rcvd[3]), .ZN (recver_n_1270));
  CKAN2D0BWP7T recver_g2901(.A1 (rdn), .A2 (clrn), .Z (recver_n_1271));
  INR2D0BWP7T recver_g2902(.A1 (no_bits_rcvd[3]), .B1
       (no_bits_rcvd[2]), .ZN (recver_n_1272));
  NR2D0BWP7T recver_g2903(.A1 (no_bits_rcvd[0]), .A2 (recver_n_1287),
       .ZN (recver_n_1274));
  NR2D0BWP7T recver_g2904(.A1 (recver_n_1306), .A2 (recver_n_1287), .ZN
       (recver_n_1276));
  INVD1BWP7T recver_g2905(.I (recver_sampling_place[3]), .ZN
       (recver_n_1285));
  INVD1BWP7T recver_g2906(.I (no_bits_rcvd[1]), .ZN (recver_n_1287));
  INVD1BWP7T recver_g2908(.I (no_bits_rcvd[0]), .ZN (recver_n_1306));
  INR3D0BWP7T recver_g2(.A1 (sampling), .B1 (no_bits_rcvd[3]), .B2
       (no_bits_rcvd[2]), .ZN (recver_n_1307));
endmodule

