set_db port:uart/clk16x .original_name {clk16x}
set_db port:uart/clrn .original_name {clrn}
set_db port:uart/rdn .original_name {rdn}
set_db port:uart/rxd .original_name {rxd}
set_db port:uart/wrn .original_name {wrn}
set_db {port:uart/d_in[7]} .original_name {d_in[7]}
set_db {port:uart/d_in[6]} .original_name {d_in[6]}
set_db {port:uart/d_in[5]} .original_name {d_in[5]}
set_db {port:uart/d_in[4]} .original_name {d_in[4]}
set_db {port:uart/d_in[3]} .original_name {d_in[3]}
set_db {port:uart/d_in[2]} .original_name {d_in[2]}
set_db {port:uart/d_in[1]} .original_name {d_in[1]}
set_db {port:uart/d_in[0]} .original_name {d_in[0]}
set_db {port:uart/d_out[7]} .original_name {d_out[7]}
set_db {port:uart/d_out[6]} .original_name {d_out[6]}
set_db {port:uart/d_out[5]} .original_name {d_out[5]}
set_db {port:uart/d_out[4]} .original_name {d_out[4]}
set_db {port:uart/d_out[3]} .original_name {d_out[3]}
set_db {port:uart/d_out[2]} .original_name {d_out[2]}
set_db {port:uart/d_out[1]} .original_name {d_out[1]}
set_db {port:uart/d_out[0]} .original_name {d_out[0]}
set_db port:uart/r_ready .original_name {r_ready}
set_db port:uart/parity_error .original_name {parity_error}
set_db port:uart/frame_error .original_name {frame_error}
set_db port:uart/t_empty .original_name {t_empty}
set_db port:uart/txd .original_name {txd}
set_db {port:uart/cnt16x[3]} .original_name {cnt16x[3]}
set_db {port:uart/cnt16x[2]} .original_name {cnt16x[2]}
set_db {port:uart/cnt16x[1]} .original_name {cnt16x[1]}
set_db {port:uart/cnt16x[0]} .original_name {cnt16x[0]}
set_db {port:uart/no_bits_rcvd[3]} .original_name {no_bits_rcvd[3]}
set_db {port:uart/no_bits_rcvd[2]} .original_name {no_bits_rcvd[2]}
set_db {port:uart/no_bits_rcvd[1]} .original_name {no_bits_rcvd[1]}
set_db {port:uart/no_bits_rcvd[0]} .original_name {no_bits_rcvd[0]}
set_db {port:uart/r_buffer[10]} .original_name {r_buffer[10]}
set_db {port:uart/r_buffer[9]} .original_name {r_buffer[9]}
set_db {port:uart/r_buffer[8]} .original_name {r_buffer[8]}
set_db {port:uart/r_buffer[7]} .original_name {r_buffer[7]}
set_db {port:uart/r_buffer[6]} .original_name {r_buffer[6]}
set_db {port:uart/r_buffer[5]} .original_name {r_buffer[5]}
set_db {port:uart/r_buffer[4]} .original_name {r_buffer[4]}
set_db {port:uart/r_buffer[3]} .original_name {r_buffer[3]}
set_db {port:uart/r_buffer[2]} .original_name {r_buffer[2]}
set_db {port:uart/r_buffer[1]} .original_name {r_buffer[1]}
set_db {port:uart/r_buffer[0]} .original_name {r_buffer[0]}
set_db port:uart/r_clk1x .original_name {r_clk1x}
set_db port:uart/sampling .original_name {sampling}
set_db {port:uart/r_data[7]} .original_name {r_data[7]}
set_db {port:uart/r_data[6]} .original_name {r_data[6]}
set_db {port:uart/r_data[5]} .original_name {r_data[5]}
set_db {port:uart/r_data[4]} .original_name {r_data[4]}
set_db {port:uart/r_data[3]} .original_name {r_data[3]}
set_db {port:uart/r_data[2]} .original_name {r_data[2]}
set_db {port:uart/r_data[1]} .original_name {r_data[1]}
set_db {port:uart/r_data[0]} .original_name {r_data[0]}
set_db {port:uart/no_bits_sent[3]} .original_name {no_bits_sent[3]}
set_db {port:uart/no_bits_sent[2]} .original_name {no_bits_sent[2]}
set_db {port:uart/no_bits_sent[1]} .original_name {no_bits_sent[1]}
set_db {port:uart/no_bits_sent[0]} .original_name {no_bits_sent[0]}
set_db {port:uart/t_buffer[7]} .original_name {t_buffer[7]}
set_db {port:uart/t_buffer[6]} .original_name {t_buffer[6]}
set_db {port:uart/t_buffer[5]} .original_name {t_buffer[5]}
set_db {port:uart/t_buffer[4]} .original_name {t_buffer[4]}
set_db {port:uart/t_buffer[3]} .original_name {t_buffer[3]}
set_db {port:uart/t_buffer[2]} .original_name {t_buffer[2]}
set_db {port:uart/t_buffer[1]} .original_name {t_buffer[1]}
set_db {port:uart/t_buffer[0]} .original_name {t_buffer[0]}
set_db port:uart/t_clk1x .original_name {t_clk1x}
set_db port:uart/sending .original_name {sending}
set_db {port:uart/t_data[7]} .original_name {t_data[7]}
set_db {port:uart/t_data[6]} .original_name {t_data[6]}
set_db {port:uart/t_data[5]} .original_name {t_data[5]}
set_db {port:uart/t_data[4]} .original_name {t_data[4]}
set_db {port:uart/t_data[3]} .original_name {t_data[3]}
set_db {port:uart/t_data[2]} .original_name {t_data[2]}
set_db {port:uart/t_data[1]} .original_name {t_data[1]}
set_db {port:uart/t_data[0]} .original_name {t_data[0]}



set_db pin:uart/sender_txd_reg/Q .original_name {sender/txd/q}
set_db pin:uart/sender_wrn_buf_clean_reg/Q .original_name {sender/wrn_buf_clean/q}
set_db pin:uart/sender_clrn_buf_reg/Q .original_name {sender/clrn_buf/q}
set_db {pin:uart/cnt16x_reg[3]/Q} .original_name {cnt16x[3]/q}
set_db pin:uart/sender_sending_reg/Q .original_name {sender/sending/q}
set_db {pin:uart/sender_no_bits_sent_reg[3]/Q} .original_name {sender/no_bits_sent[3]/q}
set_db {pin:uart/cnt16x_reg[2]/Q} .original_name {cnt16x[2]/q}
set_db {pin:uart/sender_t_buffer_reg[1]/Q} .original_name {sender/t_buffer[1]/q}
set_db {pin:uart/sender_t_buffer_reg[0]/Q} .original_name {sender/t_buffer[0]/q}
set_db {pin:uart/sender_t_buffer_reg[3]/Q} .original_name {sender/t_buffer[3]/q}
set_db {pin:uart/sender_t_buffer_reg[2]/Q} .original_name {sender/t_buffer[2]/q}
set_db {pin:uart/sender_no_bits_sent_reg[2]/Q} .original_name {sender/no_bits_sent[2]/q}
set_db {pin:uart/sender_t_buffer_reg[6]/Q} .original_name {sender/t_buffer[6]/q}
set_db {pin:uart/sender_t_buffer_reg[7]/Q} .original_name {sender/t_buffer[7]/q}
set_db {pin:uart/sender_t_buffer_reg[4]/Q} .original_name {sender/t_buffer[4]/q}
set_db {pin:uart/sender_t_buffer_reg[5]/Q} .original_name {sender/t_buffer[5]/q}
set_db pin:uart/sender_t_empty_reg/Q .original_name {sender/t_empty/q}
set_db pin:uart/sender_load_t_buffer_reg/Q .original_name {sender/load_t_buffer/q}
set_db {pin:uart/sender_t_data_reg[0]/Q} .original_name {sender/t_data[0]/q}
set_db {pin:uart/cnt16x_reg[1]/Q} .original_name {cnt16x[1]/q}
set_db {pin:uart/sender_no_bits_sent_reg[1]/Q} .original_name {sender/no_bits_sent[1]/q}
set_db {pin:uart/sender_t_data_reg[1]/Q} .original_name {sender/t_data[1]/q}
set_db {pin:uart/sender_t_data_reg[2]/Q} .original_name {sender/t_data[2]/q}
set_db {pin:uart/sender_t_data_reg[4]/Q} .original_name {sender/t_data[4]/q}
set_db {pin:uart/sender_t_data_reg[5]/Q} .original_name {sender/t_data[5]/q}
set_db {pin:uart/sender_t_data_reg[6]/Q} .original_name {sender/t_data[6]/q}
set_db {pin:uart/sender_t_data_reg[7]/Q} .original_name {sender/t_data[7]/q}
set_db {pin:uart/sender_t_data_reg[3]/Q} .original_name {sender/t_data[3]/q}
set_db pin:uart/sender_wrn_buf_reg/Q .original_name {sender/wrn_buf/q}
set_db pin:uart/sender_clrn_buf_clean_reg/Q .original_name {sender/clrn_buf_clean/q}
set_db {pin:uart/cnt16x_reg[0]/Q} .original_name {cnt16x[0]/q}
set_db {pin:uart/cnt16x_reg[0]/Q} .is_phase_inverted true
set_db {pin:uart/sender_no_bits_sent_reg[0]/Q} .original_name {sender/no_bits_sent[0]/q}
set_db {pin:uart/sender_no_bits_sent_reg[0]/Q} .is_phase_inverted true
set_db {pin:uart/sender_no_bits_sent_reg[0]/QN} .original_name {sender/no_bits_sent[0]/q}
set_db {pin:uart/sender_no_bits_sent_reg[0]/QN} .is_phase_inverted true
set_db pin:uart/recver_rxd_old_reg/Q .original_name {recver/rxd_old/q}
set_db pin:uart/recver_rxd_new_reg/Q .original_name {recver/rxd_new/q}
set_db pin:uart/recver_parity_error_reg/Q .original_name {recver/parity_error/q}
set_db pin:uart/recver_clk1x_reg/Q .original_name {recver/clk1x/q}
set_db pin:uart/recver_clk1x_reg/Q .is_phase_inverted true
set_db pin:uart/recver_clk1x_reg/QN .original_name {recver/clk1x/q}
set_db pin:uart/recver_clk1x_reg/QN .is_phase_inverted true
set_db {pin:uart/recver_r_buffer_reg[10]/Q} .original_name {recver/r_buffer[10]/q}
set_db {pin:uart/recver_r_buffer_reg[8]/Q} .original_name {recver/r_buffer[8]/q}
set_db {pin:uart/recver_r_buffer_reg[5]/Q} .original_name {recver/r_buffer[5]/q}
set_db {pin:uart/recver_r_buffer_reg[5]/Q} .is_phase_inverted true
set_db {pin:uart/recver_r_buffer_reg[5]/QN} .original_name {recver/r_buffer[5]/q}
set_db {pin:uart/recver_r_buffer_reg[5]/QN} .is_phase_inverted true
set_db {pin:uart/recver_r_buffer_reg[4]/Q} .original_name {recver/r_buffer[4]/q}
set_db {pin:uart/recver_r_buffer_reg[4]/Q} .is_phase_inverted true
set_db {pin:uart/recver_r_buffer_reg[4]/QN} .original_name {recver/r_buffer[4]/q}
set_db {pin:uart/recver_r_buffer_reg[4]/QN} .is_phase_inverted true
set_db {pin:uart/recver_r_buffer_reg[9]/Q} .original_name {recver/r_buffer[9]/q}
set_db {pin:uart/recver_r_buffer_reg[2]/Q} .original_name {recver/r_buffer[2]/q}
set_db {pin:uart/recver_r_buffer_reg[1]/Q} .original_name {recver/r_buffer[1]/q}
set_db {pin:uart/recver_r_buffer_reg[0]/Q} .original_name {recver/r_buffer[0]/q}
set_db {pin:uart/recver_r_buffer_reg[6]/Q} .original_name {recver/r_buffer[6]/q}
set_db {pin:uart/recver_r_buffer_reg[7]/Q} .original_name {recver/r_buffer[7]/q}
set_db {pin:uart/recver_r_buffer_reg[3]/Q} .original_name {recver/r_buffer[3]/q}
set_db {pin:uart/recver_r_data_reg[1]/Q} .original_name {recver/r_data[1]/q}
set_db {pin:uart/recver_r_data_reg[2]/Q} .original_name {recver/r_data[2]/q}
set_db {pin:uart/recver_r_data_reg[3]/Q} .original_name {recver/r_data[3]/q}
set_db {pin:uart/recver_r_data_reg[4]/Q} .original_name {recver/r_data[4]/q}
set_db {pin:uart/recver_r_data_reg[5]/Q} .original_name {recver/r_data[5]/q}
set_db {pin:uart/recver_r_data_reg[6]/Q} .original_name {recver/r_data[6]/q}
set_db {pin:uart/recver_r_data_reg[7]/Q} .original_name {recver/r_data[7]/q}
set_db {pin:uart/recver_r_data_reg[0]/Q} .original_name {recver/r_data[0]/q}
set_db pin:uart/recver_sampling_reg/Q .original_name {recver/sampling/q}
set_db {pin:uart/recver_sampling_place_reg[1]/Q} .original_name {recver/sampling_place[1]/q}
set_db {pin:uart/recver_sampling_place_reg[3]/Q} .original_name {recver/sampling_place[3]/q}
set_db {pin:uart/recver_sampling_place_reg[3]/Q} .is_phase_inverted true
set_db {pin:uart/recver_sampling_place_reg[2]/Q} .original_name {recver/sampling_place[2]/q}
set_db {pin:uart/recver_sampling_place_reg[0]/Q} .original_name {recver/sampling_place[0]/q}
set_db pin:uart/recver_frame_error_reg/Q .original_name {recver/frame_error/q}
set_db pin:uart/recver_frame_error_reg/Q .is_phase_inverted true
set_db pin:uart/recver_frame_error_reg/QN .original_name {recver/frame_error/q}
set_db pin:uart/recver_frame_error_reg/QN .is_phase_inverted true
set_db {pin:uart/recver_no_bits_rcvd_reg[3]/Q} .original_name {recver/no_bits_rcvd[3]/q}
set_db pin:uart/recver_r_ready_reg/Q .original_name {recver/r_ready/q}
set_db {pin:uart/recver_no_bits_rcvd_reg[2]/Q} .original_name {recver/no_bits_rcvd[2]/q}
set_db {pin:uart/recver_no_bits_rcvd_reg[1]/Q} .original_name {recver/no_bits_rcvd[1]/q}
set_db {pin:uart/recver_no_bits_rcvd_reg[0]/Q} .original_name {recver/no_bits_rcvd[0]/q}
